spring:
  application:
    name: shopfront
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: Asia/Tashkent
  flyway:
    enabled: true
  threads:
    virtual:
      enabled: true

server:
  port: 8080

app:
  shop-slug: ${SHOP_SLUG:aroma}
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_USERNAME}

logging:
  level:
    uz.azam.shopfront: DEBUG
